name: Release & Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check github.ref starts with 'refs/tags/'
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo Error! github.ref does not start with 'refs/tags'
          echo github.ref: ${{ github.ref }}
          exit 1
      - name: Set version number environment variable
        env:
          github_ref: ${{ github.ref }}
        run: |
          ref="${github_ref:10}"
          echo $ref
          echo "ref=$ref" >> $GITHUB_ENV
      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm@10
        run: npm i -g npm@10
      - name: Install modules
        run: npm ci
      - name: Build
        run: npm run build
#      - name: Publish to npm
#        run: npm publish --access public
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure package name, url, and version
        env:
          github_repo: ${{ github.repository }}
        run: node tools/updateurl $github_repo $ref
      - name: Clean package.json
        run: node tools/prepare-publish
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
